
name: generic-build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-2019
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore Packages
      run: nuget restore Rubeus.sln

    - name: Build Solution
      run: |
        msbuild.exe Rubeus.sln
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: D:\a\Rubeus\Rubeus\Rubeus\bin\Debug\Rubeus.exe
        retention-days: 5
